name: Shailaja Akella
description: Graduate student in Electrical and Computer Engineering. <p style = "color:white"> <a href="http://www.cnel.ufl.edu/"> Computational NeuroEngineering Lab </a>, University of Florida. </p>
markdown: kramdown
theme: jekyll-theme-cayman
