name: Shailaja Akella
description: Graduate student in Electrical and Computer Engineering.<p><u><a href="http://www.cnel.ufl.edu/"> Computational NeuroEngineering Lab, University of Florida.</a></u></p> 
theme: jekyll-theme-cayman
google_analytics: G-PGTDEWLECX
