name: Shailaja Akella
description: Graduate student in Electrical and Computer Engineering. <br> <a href="http://www.cnel.ufl.edu/"> Computational NeuroEngineering Lab </a> , University of Florida.
markdown: kramdown
theme: jekyll-theme-cayman
